syntax = "proto3";

package notification;

service NotificationService {
  rpc SendConfirmation (ConfirmationRequest) returns (AckResponse);
  rpc SendReleaseNotification (ReleaseRequest) returns (AckResponse);
}

message ConfirmationRequest {
  string email = 1;
  string confirm_token = 2;
  string repo = 3;
}

message Release {
  string tag_name = 1;
  string name = 2;
  string html_url = 3;
  string published_at = 4;
}

message ReleaseRequest {
  string email = 1;
  string unsubscribe_token = 2;
  string repo = 3;
  Release release = 4;
}

message AckResponse {
  string status = 1;
  string job_id = 2;
}
